stages:
  data_prepare:
    cmd: python -m src.stages.data_prepare --config=params.yaml
    deps:
    - src/stages/data_prepare.py
    params:
    - base
    - data_load
    outs:
    - data/processed/prepare_online_retail.csv
  featurize:
    cmd: python -m src.stages.featurize --config=params.yaml
    deps:
    - data/processed/prepare_online_retail.csv
    - src/stages/featurize.py
    params:
    - base
    - data_load
    - featurize
    outs:
    - data/processed/featured_online_retail.csv
  scaling:
    cmd: python -m src.stages.data_scaling --config=params.yaml
    deps:
    - data/processed/featured_online_retail.csv
    - src/stages/data_scaling.py
    params:
    - base
    - featurize
    - scaling
    outs:
    - data/processed/norm_online_retail.csv
  train:
    cmd: python -m src.stages.train --config=params.yaml
    deps:
      - data/processed/norm_online_retail.csv
      - src/stages/train.py
    params:
      - base
      - data_load
      - scaling
      - train
    outs:
      - models/model.pkl
  evaluate:
    cmd: python -m src.stages.evaluate --config=params.yaml
    deps:
    - data/processed/norm_online_retail.csv
    - data/processed/featured_online_retail.csv
    - models/model.pkl
    - src/stages/evaluate.py
    params:
    - base
    - data_load
    - scaling
    - train
    - evaluate
    outs:
    - data/final/final_online_retail.csv
