base:
  random_state: 42
  log_level: INFO

data_load:
  dataset_csv: 'data/raw/online_retail_raw.csv'
  dataset_prepare: 'data/processed/prepare_online_retail.csv'
  encoding: 'ISO-8859-1'

featurize:
  features_path: 'data/processed/featured_online_retail.csv'

elbow:
  graph_path: 'docs/elbow.png'
  norm_path: 'data/processed/norm_online_retail.csv'
  rfm_path: 'data/processed/rfm_online_retail.csv'

train:
  graph_path: 'docs/cluster.png'
  n_clusters: 3

