name: ML Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  mlops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
        make dependencies_ci

    - name: Run Pipeline
      run: |
        make run_pipeline_ci
