name: ML Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  mlops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
        make dependencies_ci

    - name: Pull Raw Data
      run: |
        source $(poetry env info --path)/bin/activate
        make pull_raw_data

    - name: Run Pipeline
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        source $(poetry env info --path)/bin/activate
        make run_pipeline_ci

    - name: Push Results
      if: github.event_name == 'push'
      run: |
        source $(poetry env info --path)/bin/activate
        make upload_results
